---
- include: rbenv.yml

- name: Install bundler
  command: /bin/bash -l -c 'gem install bundler --no-ri --no-rdoc'
  sudo_user: '{{ user_name }}'

- name: bundle install
  command: /bin/bash -l -c 'bundle install' chdir={{ app_path }}
  sudo_user: '{{ user_name }}'
  when: target == 'virtualbox'
